### ISSUE TITLE
Android App Crashes

### ISSUE THREAD

**Issue by jkwong888** [ibm-cloud-architecture/refarch-cloudnative-bluecompute-mobile#7]
Android app is crashing on itemlist and item details.  This is because the APIC URL is not formed correctly:

https://api.us.apiconnect.ibmcloud.com/centusibmcom-cloudnative-qa/bluecomputeapi/items

it's missing a slash between "bluecompute" and "api".  This is due to the way the data is stored in cloudant (the image URLs do not have leading slashes).

**Comment by vbudi000** [comment]
This was changed from the time it was initially built. Will post an update on this.
